repos:
  - repo: local
    hooks:
      # Run the linter.
      - id: ruff
        name: ruff
        entry: ruff check
        types:
          - python
        language: python
      # Run the formatter.
      - id: ruff-format
        name: ruff format
        entry: ruff format
        types:
          - python
        language: python
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types:
          - python
      - id: pytest
        name: pytest
        entry: pytest
        args: [--cov]
        language: system
        pass_filenames: false
        types:
          - python
        always_run: true
